version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8022:8080"
    environment:
      - VITE_API_URL=http://backend:5002
    depends_on:
      - backend
    networks:
      - wallet-network

  backend:
    build:
      context: ../backend-wallet-decentralized
      dockerfile: Dockerfile
    ports:
      - "5002:3000"
    environment:
      - PORT=3000
      - BLOCKCYPHER_API_KEY=${BLOCKCYPHER_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge
